# store for hardcoded variables

clock12 = {0: ([0.5, 0.9]),
             1: ([0.5, 0.1]),
             2: ([0.9, 0.5]),
             3: ([0.1, 0.5]),
             4: ([0.84641016, 0.7       ]),
             5: ([0.3       , 0.84641016]),
             6: ([0.15358984, 0.3       ]),
             7: ([0.7       , 0.15358984]),
             8: ([0.7       , 0.84641016]),
             9: ([0.15358984, 0.7       ]),
             10: ([0.3       , 0.15358984]),
             11: ([0.84641016, 0.3       ])}


snames = {'TOS':"The Original Series",
            'TNG':"The Next Generation", 
            'DS9':"Deep Space 9", 
            'VOY':"Voyager",
            'ENT':"Enterprise"
            }

col_dict = {'TNG':{'PICARD': 'red',
                     'RIKER': 'red',
                     'DATA': 'orange',
                     'LAFORGE': 'orange',
                     'WORF': 'orange',
                     'CRUSHER': 'blue',
                     'TROI': 'blue',
                     'WESLEY': 'red',
                     'Q': 'grey',
                     'COMPUTER': 'grey',
                     'TASHA': 'orange',
                     'O_BRIEN': 'orange'},
            
            'DS9':{'BASHIR': 'blue',
                     'DAX': 'blue',
                     'GARAK':'gray',
                     'JAKE':'gray',
                     'KIRA':'red',
                     'NOG':'orange',
                     'ODO':'gray',
                     'O_BRIEN':'orange',
                     'QUARK':'gray',
                     'ROM':'gray',
                     'SISKO':'red',
                     'WORF':'red'},
            
            'VOY':{'BARCLAY':'orange',
                 'CHAKOTAY':'red',
                 'COMPUTER':'gray',
                 'EMH':'blue',
                 'JANEWAY':'red',
                 'KES':'gray',
                 'KIM':'orange',
                 'NEELIX':'gray',
                 'PARIS':'red',
                 'SEVEN':'blue',
                 'TORRES':'orange',
                 'TUVOK':'orange'
                  },
            
            'TOS':{'KIRK':'orange',
                  'SPOCK':'blue',
                  'MCCOY':'blue',
                  'SCOTT':'red',
                  'PIKE':'orange',
                  'SULU':'orange',
                  'UHURA':'red',
                   'CHEKOV':'orange',
                   'TRELANE':'gray',
                   'COMMANDER':'gray',
                   'CHAPEL':'gray',
                   'MUDD':'gray',
                   'COMPUTER':'gray',
                  },
            'ENT':{'ARCHER':'orange', 
                   'HOSHI':'blue', 
                   'PHLOX':'gray', 
                   'REED':'red', 
                   'SHRAN':'gray',
                   'TRAVIS':'orange', 
                   'TUCKER':'red', 
                   'T_POL':'gray',
                   'DEGRA':'gray',
                   'SOONG':'gray',
                   'MALIK':'gray',
                   'SOVAL':'gray'
                   
                   }
           }