# store for hardcoded variables

grey = 'rgb(40,40,40)'
orange = 'rgb(179,138,0)'
red = 'rgb(209,50,35)'
blue = 'rgb(35,87,209)'
brown = 'rgb(100,50,35)'
lightgrey = 'rgb(70,70,70)'

snames = {'TOS': "Star Trek: The Original Series",
          'TNG': "Star Trek: The Next Generation",
          'DS9': "Star Trek: Deep Space 9",
          'VOY': "Star Trek: Voyager",
          'ENT': "Star Trek: Enterprise",
          'TOSm': "Movies (The Original Series)",
          "TNGm": 'Movies (The Next Generation)',
          'JJA': "Movies (Kelvin timeline)"
          }


max_node_map = {'ENT': 12, 'TOS': 12, "TNG": 20, 'VOY': 20,
                'DS9': 20, 'TOSm': 16, 'TNGm': 16, 'JJA': 16}
def_node_map = {'ENT': 8, 'TOS': 8, "TNG": 12, 'VOY': 12,
                'DS9': 12, 'TOSm': 16, 'TNGm': 16, 'JJA': 16}


col_dict = {'TNG': {'PICARD': red,
                    'RIKER': red,
                    'DATA': orange,
                    'LAFORGE': orange,
                    'WORF': orange,
                    'CRUSHER': blue,
                    'TROI': blue,
                    'WESLEY': red,
                    'Q': grey,
                    'COMPUTER': lightgrey,
                    'TASHA': orange,
                    "O'BRIEN": orange,
                    'PULASKI': blue,
                    'GUINAN': brown,
                    'LWAXANA': brown,
                    'RO': red,
                    'BARCLAY': orange,
                    'VASH': brown,
                    'ALEXANDER': brown,
                    "K'EHLEYR": brown
                    },

            'DS9': {'BASHIR': blue,
                    'DAX': blue,
                    'GARAK': grey,
                    'JAKE': brown,
                    'KIRA': brown,
                    'NOG': orange,
                    'ODO': brown,
                    "O'BRIEN": orange,
                    'QUARK': brown,
                    'ROM': brown,
                    'SISKO': red,
                    'WORF': red,
                    'DUKAT': grey,
                    'EZRI': blue,
                    'WEYOUN': grey,
                    'WINN': brown,
                    'KEIKO': brown,
                    'MARTOK': brown,
                    'DAMAR': grey,
                    'ZEK': brown
                    },

            'VOY': {'BARCLAY': orange,
                    'CHAKOTAY': red,
                    'COMPUTER': lightgrey,
                    'EMH': blue,
                    'JANEWAY': red,
                    'KES': brown,
                    'KIM': orange,
                    'NEELIX': brown,
                    'PARIS': red,
                    'SEVEN': blue,
                    'TORRES': orange,
                    'TUVOK': orange,
                    'ICHEB': brown,
                    'NAOMI': brown,
                    'SESKA': grey,
                    'Q': grey,
                    'MICHAEL': orange,
                    'SHANNON': brown,
                    'QUEEN': grey,
                    'IDEN': brown
                    },

            'TOS': {'KIRK': orange,
                    'SPOCK': blue,
                    'MCCOY': blue,
                    'SCOTT': red,
                    'PIKE': orange,
                    'SULU': orange,
                    'UHURA': red,
                    'CHEKOV': orange,
                    'TRELANE': grey,
                    'COMMANDER': red,
                    'CHAPEL': blue,
                    'MUDD': grey,
                    'COMPUTER': lightgrey,
                    },


            'JJA': {'KIRK': orange,
                    'SPOCK': blue,
                    'MCCOY': blue,
                    'SCOTT': red,
                    'PIKE': orange,
                    'SULU': orange,
                    'UHURA': red,
                    'CHEKOV': orange,
                    'GEORGE KIRK': blue,
                    'SPOCK (PRIME)': blue,
                    'NERO': grey,
                    'KHAN': grey,
                    'MARCUS': blue,
                    'KRALL': grey,
                    'JAYLAH': grey,
                    'WINONA': brown
                    },

            'TOSm': {'KIRK': red,
                     'SPOCK': blue,
                     'MCCOY': blue,
                     'SCOTT': red,
                     'SULU': orange,
                     'UHURA': red,
                     'CHEKOV': orange,
                     'KHAN': grey,
                     'VALERIS': red,
                     'CHANG': grey,
                     'DAVID': brown,
                     'DECKER': blue,
                     'GILLIAN': brown,
                     'KRUGE': grey,
                     'SAAVIK': red,
                     'SYBOK': brown
                     },

            'TNGm': {'ANIJ': brown,
                     'BORG-QUEEN': grey,
                     'COCHRANE': brown,
                     'CRUSHER': blue,
                     'DATA': orange,
                     'DOUGHERTY': red,
                     'KIRK': red,
                     'LAFORGE': red,
                     'LILY': brown,
                     'PICARD': red,
                     'RIKER': red,
                     "RU'AFO": grey,
                     'SHINZON': grey,
                     'SORAN': grey,
                     'TROI': blue,
                     'WORF': red},

            'ENT': {'ARCHER': orange,
                    'HOSHI': blue,
                    'PHLOX': brown,
                    'REED': red,
                    'SHRAN': grey,
                    'TRAVIS': orange,
                    'TUCKER': red,
                    "T'POL": brown,
                    'DEGRA': grey,
                    'SOONG': grey,
                    'MALIK': grey,
                    'SOVAL': brown

                    }
            }
